# -*- coding: utf-8 -*-
"""literacy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xNiMu8M56qWOmyeVZsoO80XBvdqtX3Z2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly
import plotly.express as px
import plotly.graph_objects as go
df = pd.read_csv(r"D:\honor\finaldata.csv", encoding="ISO-8859-1")

df

df1_literacy =df.sort_values(by='literacy').reset_index()

df1_literacy

df_lit_rev=df.sort_values(by="literacy",ascending=False).reset_index()
df_lit_rev

df.info()

fig2=px.pie(df_lit_rev.head(20),values="literacy",names="Countries and areas" ,title="pecentage of top 20 countries in literacy")
fig2.update_traces(textposition='outside',textinfo='percent+label')

fig1=px.bar(df.head(10),y='literacy',x='Countries and areas',title='bar of 10 countries in alphabetical order',color='Countries and areas')
fig1

# Bubble Chart using Plotly
fig3 = px.scatter(df_lit_rev.head(20), x="Countries and areas", y="literacy",size='literacy',
	               color="Countries and areas",
                 hover_name="Countries and areas", log_x=False, size_max=60)
fig3.update_layout(title='Bubble Plot top 20countries in literacy',xaxis_title='Countries and areas',yaxis_title='literacy rate')

fig4=px.bar(df_lit_rev.head(10),y='Birth_Rate',x='Countries and areas',title='barchart  of birth rates of top 10 countries in literacy',color='Countries and areas')
fig4

fig5=px.line(df_lit_rev.head(20),x='Countries and areas',y=['male literacy','female literacy'],title='male literacy vs female literacy in top 20 countries in literacy',line_shape='spline')
fig5.update_yaxes(title='male vs female')

fig6=px.line(df1_literacy.head(20),x='Countries and areas',y=['male literacy','female literacy'],title='male literacy vs female literacy in bottom 20 countries in literacy',line_shape='spline')
fig6.update_yaxes(title='male vs female')

fig7=px.line(df_lit_rev,x='Countries and areas',y=['male literacy','female literacy'],title='male literacy vs female literacy top to bottom in literacy',line_shape='spline')
fig7.update_yaxes(title='male vs female')

# Assuming df is your DataFrame
fig8 = px.bar(df, x='Countries and areas', y=['male literacy', 'female literacy'],
             title='Literacy Rates (Male and Female) by Country',
             labels={'value': 'Literacy Rate', 'variable': 'Gender', 'Countries and areas': 'Countries'})

# Update y-axis title
fig8.update_yaxes(title_text='Literacy Rate')

# Show the figure
fig8

fig9 = px.line(df,x='Countries and areas',y='Birth_Rate')
fig9

fig10 = px.scatter(df,x='Countries and areas',y='Birth_Rate')
fig10

fig11= px.bar(df,x='Countries and areas',y='Birth_Rate')
fig11

fig12 = px.scatter_3d(df_lit_rev,x='Countries and areas',y='Birth_Rate',z='literacy')
fig12

fig13=px.line(df_lit_rev,x='Countries and areas',y=['primary-enollment','secondary-enrollment'],title='primary enrollment vs secondary enrollment in different countries of literacy top to bottom in literacy',line_shape='spline')
fig13.update_yaxes(title='primary vs secondary enrollment')

fig14=px.line(df_lit_rev,x='Countries and areas',y=['Unemployment_Rate' , 'literacy'],title='unemployment rate vs literacy in different countries of literacy top to bottom in literacy',line_shape='spline')
fig14.update_yaxes(title='unemployment vs literacy')

'''fig1.show()
fig2.show()
fig3.show()
fig4.show()
fig5.show()
fig6.show()
fig7.show()
fig8.show()
fig9.show()
fig10.show()
fig11.show()
fig12.show()
fig13.show()
fig14.show()'''


import dash
from dash import dcc, html
import plotly.express as px
import pandas as pd

# Load your dataset
df = pd.read_csv("finaldata.csv", encoding="ISO-8859-1")


# Create Dash app
app = dash.Dash(__name__)
app.title="analysis of literacy rates"

# Define layout
app.layout = html.Div(children=[
    html.H1(children='LITERACY RATES'),
  
    
#fig1
    dcc.Graph(
        id='fig1',
        figure=px.pie(df_lit_rev.head(20),values="literacy",names="Countries and areas" ,title="pecentage of top 20 countries in literacy")
    ),
    #fig2
    dcc.Graph(
        id='fig2',
        figure=px.bar(df.head(10),y='literacy',x='Countries and areas',title='bar of 10 countries in alphabetical order',color='Countries and areas')
    ),
    #fig3
    dcc.Graph(
        id='fig3',
        figure=px.scatter(df.head(20), x="Countries and areas", y="literacy", size='literacy',
                          color="Countries and areas", hover_name="Countries and areas",
                          log_x=False, size_max=60,title='Bubble Plot top 20countries in literacy')
    ),
    #fig4
    dcc.Graph(
        id='fig4',
        figure=px.bar(df_lit_rev.head(10),y='Birth_Rate',x='Countries and areas',title='barchart  of birth rates of top 10 countries in literacy',color='Countries and areas')
    ),
    
    #fig5
    dcc.Graph(
        id='fig5',
        figure=px.line(df_lit_rev.head(20),x='Countries and areas',y=['male literacy','female literacy'],title='male literacy vs female literacy in top 20 countries in literacy',line_shape='spline')
    ),
    #fig6
    dcc.Graph(
        id='fig6',
        figure=px.line(df1_literacy.head(20),x='Countries and areas',y=['male literacy','female literacy'],title='male literacy vs female literacy in bottom 20 countries in literacy',line_shape='spline')
    ),
    #fig7
    dcc.Graph(
        id='fig7',
        figure=px.line(df_lit_rev,x='Countries and areas',y=['male literacy','female literacy'],title='male literacy vs female literacy top to bottom in literacy',line_shape='spline')
    ),
    #fig8
    dcc.Graph(
        id='fig8',
        figure=px.bar(df, x='Countries and areas', y=['male literacy', 'female literacy'],
             title='Literacy Rates (Male and Female) by Country',
             labels={'value': 'Literacy Rate', 'variable': 'Gender', 'Countries and areas': 'Countries'})
    ),
    
    dcc.Graph(
        id='fig9',
        figure=px.line(df,x='Countries and areas',y='Birth_Rate')
    ),
    
    dcc.Graph(
        id='fig10',
        figure=px.scatter(df,x='Countries and areas',y='Birth_Rate')
    ),
    
    dcc.Graph(
        id='fig11',
        figure=px.bar(df,x='Countries and areas',y='Birth_Rate')
    ),
    
    dcc.Graph(
        id='fig12',
        figure=px.scatter_3d(df_lit_rev,x='Countries and areas',y='Birth_Rate',z='literacy')
    ),
    
    dcc.Graph(
        id='fig13',
        figure=px.line(df_lit_rev,x='Countries and areas',y=['primary-enollment','secondary-enrollment'],title='primary enrollment vs secondary enrollment in different countries of literacy top to bottom in literacy',line_shape='spline')
    ),
    
    dcc.Graph(
        id='fig14',
        figure=px.line(df_lit_rev,x='Countries and areas',y=['Unemployment_Rate' , 'literacy'],title='unemployment rate vs literacy in different countries of literacy top to bottom in literacy',line_shape='spline')
    ),
      html.Div(html.A('click here for data', href='https://drive.google.com/file/d/1sUW1CVj8p-ZhPiiRggetahTJegeNIb2V/view?usp=sharing')),
    


  

])

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)
